#!/bin/sh

VERSION=v0.2-alpha
DST_DIR=.cradle
DST_FILE=$DST_DIR/cradle.hpp
DST_SHA256="08a98cb5136dbf670a1bc40683c0b6284ac0ce70a2009a9c135bf55f53fd4f97" # Leave empty to ignore
BUILD_DIR=build

if [ -z "$CXX" ]; then
	echo "Must define environment variable \$CXX to point a valid compiler."
	exit
fi

mkdir -p $DST_DIR
mkdir -p $BUILD_DIR

if [ ! -f $DST_FILE ]; then
	wget https://github.com/mohaque0/cradle/releases/download/$VERSION/cradle.hpp -O $DST_FILE
	get_result=$?

	if [ $get_result -ne 0 ]; then
		echo "Error fetching builder version $VERSION."
		exit
	fi
fi

actualHash=`sha256sum $DST_FILE | cut -f 1 -d" "`
if [ "$DST_SHA256" != "" ] && [ "$DST_SHA256" != "$actualHash" ]; then
	echo "Downloaded file hash $actualHash doesn't match the expected $DST_SHA256."
	exit
fi

echo "Compiling Cradle..."
$CXX -g -I$DST_DIR build.cpp -std=c++14 -o $BUILD_DIR/cradle

$BUILD_DIR/cradle $@
